# Generated by Django 5.2.5 on 2025-10-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
