# Generated by Django 5.2.5 on 2025-10-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0003_alter_portfolio_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
    ]
