# Generated by Django 5.2.5 on 2025-10-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0004_remove_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
