# Generated by Django 5.2.5 on 2025-10-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0007_portfolio_description2_portfolio_description3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description6',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description7',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description8',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description9',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image9',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title6',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title7',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title8',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='title9',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('category', models.CharField(choices=[('app', 'App'), ('product', 'Product'), ('branding', 'Branding')], max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kelly_app.portfolio')),
            ],
        ),
    ]
