# Generated by Django 5.2.5 on 2025-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0008_remove_portfolio_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
