# Generated by Django 5.2.5 on 2025-10-01 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0009_portfolio_image_portfolio_link_delete_portfolioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('category', models.CharField(choices=[('app', 'App'), ('product', 'Product'), ('branding', 'Branding')], max_length=50)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kelly_app.portfolio')),
            ],
        ),
    ]
