# Generated by Django 5.2.5 on 2025-10-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0010_remove_portfolio_image_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_images/'),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
