# Generated by Django 5.2.5 on 2025-10-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0011_portfolio_image_delete_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], default='app', max_length=20),
        ),
    ]
