# Generated by Django 5.2.5 on 2025-10-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelly_app', '0013_portfolio_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=50),
        ),
    ]
